server:
  port: 8083
spring:
#  devtools:
#    restart:
#      enabled: true
#      exclude: META-INF/
#  thymeleaf:
#    cache: false
  sql:
    init:
      mode: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 911368169umid
    url: jdbc:postgresql://localhost:5432/online_chat
debug: true
auth:
  token:
    secret: 191ca4e9c30b7dbb44788dac3822c3f5
    cookie: token
    expire: 7200000
