server:
  port: 8083
spring:
#  devtools:
#    restart:
#      enabled: true
#      exclude: META-INF/
#  thymeleaf:
#    cache: false
  sql:
    init:
      mode: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
#    username: postgres
    username: zxdlovpimthvyr
#    password: 911368169umid
    password: 12b64b6dcfe6476ecf744c3791022ec1782f6df955e527d5cbb8ae1422e9f5fd
#    url: jdbc:postgresql://localhost:5432/online_chat
    url: postgres://zxdlovpimthvyr:12b64b6dcfe6476ecf744c3791022ec1782f6df955e527d5cbb8ae1422e9f5fd@ec2-63-35-156-160.eu-west-1.compute.amazonaws.com:5432/dcqk64p0sf2dcl
debug: true
auth:
  token:
    secret: 191ca4e9c30b7dbb44788dac3822c3f5
    cookie: token
    expire: 7200000
